
   
on:
  push:
    branches:
      - main
jobs:
  configAPI_update:
    runs-on: ubuntu-latest
    name: Update Dev Tracking Plan
    steps:
      - name: Config API Action
        id: hello
        uses: rishnair/Segment-Tracking-Plan@main
        with:
         Tracking-Plan-Type: 'Dev'
