# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name: 

jobs:
  build:
    name: do-the-thing
    runs-on: ubuntu-latest
    steps:
    - name: run script
      run: |
        npm install
        node render.js
