# This is a basic workflow to help you get started with Actions

name: On Merge

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event.pull_request.merged == 'true'

# The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Output current branch name & date
        uses: satackey/action-js-inline@v0.0.2
        id: getdata
        with:
    # Edit the following line to install packages required to run your script.
          required-packages: axios
            script:|
              const core = require('@actions/core')
              const fs = require(‘fs’)  
              
              fs.readFile('protocols-diffs/src/analytics-autogenerated/plan.json', 'utf8', (err, jsonString) => {
                if (err) {
                    console.log("File read failed:", err)
                    return
                }
                try{
                const json = JSON.parse(jsonString)
                console.log(json)
                }
                console.log('File data:', jsonString) 
              })
