name: Update QA TP
on:
  release:
    types: [published]
jobs:
  configAPI_update:
    runs-on: ubuntu-latest
    name: Update Dev Tracking Plan
    steps:
      - name: Config API Action
        id: hello
        uses: segment-services-eng/DEMO---TP-Repo@main
        with:
         Tracking-Plan-Type: 'QA'
         Segment-Token: ${{ secrets.SEGMENT_CONFIG_API_TOKEN }}
