name: Update plan.json and create branch

on:
  repository_dispatch:
    types:
      - tracking_plan_updated

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello World"
    - name: Create branch
      uses: peterjgrainger/action-create-branch@v1.0.0
      with:
        branch: ${{ github.run_id }}